### ISSUE TITLE
Configuration number clash with gnea lpc build

### ISSUE THREAD

**Issue by jappiemike** [Schildkroet/GRBL-Advanced#11]
I noticed that your $140,$141 and $142 clash with the configuration numbers in https://github.com/gnea/grbl-LPC , is this going to be a problem further down the track for you?
Cheers
Mike

**Comment by Schildkroet** [comment]
This would only be a problem, if you use some kind of GUI etc. which asumes, that $140 ... is amp control and therefor sets wrong values.
Otherwise it won't have any effect (because i won't add I2C amp control)
