### ISSUE TITLE
Where are function/pin assignments defined in?

### ISSUE THREAD

**Issue by mikemaikaefer** [Schildkroet/GRBL-Advanced#14]
More a question than an issue: I'm looking for some cpu_map.h-type file, means a file where functions can be assigned to the different pins of the MCU. Where can I find that here?

Thanks!

**Comment by Schildkroet** [comment]
Currently there is no real pin map. Pin config is done in HAL/GPIO/GPIO.c

**Comment by mikemaikaefer** [comment]
...and another question: how about defines for the serial port the communication is done with - where/how can the USART be chosen?

Thanks :-)

**Comment by Schildkroet** [comment]
Baudrate is defined in grbl/Config.h
Usart/STDOUT in HAL/USART/USART.h. But you also have to change the ISR
