### ISSUE TITLE
GRBL-Advanced

### ISSUE THREAD

**Issue by serg1958** [Schildkroet/GRBL-Advanced#15]
Good afternoon. 
I apologize for the bad English.
I have a free Nucleo 401RE card. Will your firmware work?
Sincerely, Sergey.

**Comment by Schildkroet** [comment]
Both MCUs are from F4 familiy, so it might work. But i don't know. I don't have a F401.

**Comment by serg1958** [comment]
Thanks for the quick reply.
401Re-84 Mhz, I think I need to program timers? 
Your program for 115200 b/s does not work.
Can I tell where in the program I need to make changes?
Sincerely, Sergey.

**Comment by Schildkroet** [comment]
Usually it should be enough to update the startup script https://github.com/Schildkroet/GRBL-Advanced/blob/software/HAL/STM32/system_stm32f4xx.c
All CLKs are calculated based on that values

And the startup script must be updated with the proper memory sizes

**Comment by serg1958** [comment]
Ok. 
Many thanks.
Sincerely, Sergey.

**Comment by nsiatras** [comment]
Did you manage to make it run on the 401 board?
PS. I have compiled it and it runs but I think some values are incorrect.
I loose steps etc.. and the probe doesn't work very good

**Comment by nsiatras** [comment]
PS.  Can someone help me make the corect values on the system_Stem32f4xx.c ?

**Comment by serg1958** [comment]
Thank you so much for your help. I am currently using STM32F103C8T6 for GRBL. Everything works very well. The subject needs to be closed.
All thanks.
Sergey.
