### ISSUE TITLE
SPI support for Trinamic stepsticks

### ISSUE THREAD

**Issue by fantasmag0ria** [Schildkroet/GRBL-Advanced#18]
It would be really nice if software was able to use TMCs driver SPI-configuration. 
Especially now, when Trinamic released new TMC5161 drivers capable of running at 4A.
https://www.trinamic.com/products/integrated-circuits/details/tmc5161/

The 2130s had 'headless' mode and were able to run without SPI. 5161s are lacking this feature afaik.

**Comment by Schildkroet** [comment]
There is a working SPI driver in HAL-Directory, which you can use to configure the drivers. Currently i don't intend to implement external drivers.
