### ISSUE TITLE
How to compile for STM401

### ISSUE THREAD

**Issue by jappiemike** [Schildkroet/GRBL-Advanced#2]
Hello Schildkroet, I'm just about finished the mechanical side of my router and came across your GRBL port to the STM board. I have a couple of these lying around that I've not really used or followed for awhile. I downloaded your code and tried to compile it in the MBed online compiler and have lots of errors about unfound files. I know they are in your code but I would suspect some of them are also MBed library files (Error: Cannot open source input file "stm32f4xx_conf.h": No such file or directory in "HAL/SPI/SPI.h", Line: 6, Col: 29). My question is, shouldn't I be using the library files as this would mean that updates would be included when I compile again later? Any help for a novice would be greatly appreciated.
JappieMike

**Comment by Schildkroet** [comment]
Hello,
this code is supposed to be compiled with EmBitz IDE (Open .ebp Project, select 'Release Target' and hit compile).
You have probably 2 problems:
- EmBitz sets several compiler defines like 'USE_STDPERIPH_DRIVER' which are needed mostly for SPL. You would have to go through the .ebp file and manually add these defines to your project.
- EmBitz includes ALL directories while compiling. So i can add all inludes just with #include "myfile.h" and it will be found. If you don't pass all directories to the compiler, you have to write the relative path of the include from the current directory like #include "../../dir/subdir/myfile.h"

**Comment by jappiemike** [comment]
Hi and thanks  for the quick reply. I didn't think it was going to be easy, I guess I'll have to go through all the headers and work out what needs changing to work with the online compiler. 
Cheers
JappieMike
