### ISSUE TITLE
Not an isuue but a question..

### ISSUE THREAD

**Issue by salvato** [Schildkroet/GRBL-Advanced#20]
Hi, many compliments for your port of GRBL.
I've a question about Laser mode:
in an old issue I've read that at that time you had  not yet ported the laser mode to STM32.
It is still true nowaday ?
Tank you

Gabriele

**Comment by Schildkroet** [comment]
Yes, nothing changed since than about laser. But according to Issue #4 , laser seems to work.

**Comment by salvato** [comment]
Thank you !
I'll test asap.
Gabriele
