### ISSUE TITLE
Hold Status Issue (STM32F429ZI)

### ISSUE THREAD

**Issue by Lim-Seunghwan** [Schildkroet/GRBL-Advanced#21]
Hello Schildkroet!

With your advice, I uploaded GRBL on my Nucleo STMF429ZI.(USART2 -> USART3 was a solution)
So I can get response from Candle2(also your version) like below.

![candle2 hold](https://user-images.githubusercontent.com/11681577/60647075-d8605700-9e77-11e9-9847-c3b96fa1441e.PNG)

And now I have one problem in board status. 
With STMF411RE, after press 'reset' button, status change to 'Idle'.
But with STMF429ZI, it does not change to 'Idle', stay in 'Hold' status.

Is there more things to change for use STMF429ZI?

Best Regards,
Seunghwan.

**Comment by Schildkroet** [comment]
Hello,
it seems the 'Feed Hold Pin' is triggered. Maybe there is some external peripheral on this pin with the F429.

**Comment by Lim-Seunghwan** [comment]
Thank you for answer. I solve this problem by change the 'Feed Hold Pin'.
