### ISSUE TITLE
Troubles with connecting to GRBL

### ISSUE THREAD

**Issue by czapeczek** [Schildkroet/GRBL-Advanced#23]
I am having regular problems with connecting to GRBL. After I deploy the binary, everything is fine and I can use GRBL. But after turning it off and then on - I cannot connect. There is no response on Serial port from the device. 

I really doubt that this is a bug but no clue how to track this. Did anyone encountered such problem?

**Comment by Schildkroet** [comment]
How do you flash the binary? Do you build it yourself?

**Comment by czapeczek** [comment]
I build it with EmBitz, no warnings
Flashing by copying the bin file to the NUCLEO drive which appears after you connect it to the USB

I tried to see how does that work and it's really weird. 
I am not able to simply send a new build and get thing working. 
I need to upload some different code first. Like simple led blinking code. Then I can send GRBL Advanced and only after that I can connect

**Comment by czapeczek** [comment]
Embitz 1.11 to be more precise

**Comment by Schildkroet** [comment]
When building with Embitz, make sure to select 'Release' as target. There will be a HEX file in the output folder.
Flash the HEX with ST-Link Utility or STM32CubeProg.

**Comment by czapeczek** [comment]
Nothing changes. I might buy another nucleo and see if there's a difference. But sounds really odd. 
Thanks for your help. If anything comes up to your mind I'll appreciate help

Cheers
Filip

**Comment by czapeczek** [comment]
@Schildkroet I upgraded ST link firmware and it gives me some hopes. I will let you know in 1-2 days if it's stable
