### ISSUE TITLE
Small angle approximation leftover from the ATmega328P optimization days?

### ISSUE THREAD

**Issue by fenderrex** [Schildkroet/GRBL-Advanced#26]
Small-angle approximation may be used to reduce computation overhead further. A third-order approximation (second-order sin() has too much error) holds for most, if not, all CNC applications.
https://github.com/gnea/grbl/blame/eefe2bb95bb7b21ec2bb87e6ab6e20747e1626c4/grbl/motion_control.c#L135
I know the STM32F401RE has some cool specialized clock tools for the (DMA) direct memory access could hold larger planner buffers and could open the best implementation for g5.1 g5.2
http://linuxcnc.org/docs/html/gcode.html

**Comment by Schildkroet** [comment]
ATM i don't plan to modify the internal calculations (chamnit is already working on a better version), but since grbl is open-source you are free to modify it to your needs yourself
