### ISSUE TITLE
A Achse? error 20..

### ISSUE THREAD

**Issue by hitchhiker85** [Schildkroet/GRBL-Advanced#32]
Sorry... ich  hab nun mein f411 ;)

aber irgendwie kann ich die A Achse nicht benutzen.. was mach ich falsch?

g91
g1 a200 f100

und dann kommt error 20...

gibts eine alternative kontaktmöglichkeit_?

**Comment by Schildkroet** [comment]
Hast du `#define USE_MULTI_AXIS` in Config.h aktiviert?

**Comment by hitchhiker85** [comment]
ja!

und auch neu geflashed!
gibts da ein bug?!

**Comment by hitchhiker85** [comment]
Moment!

Ich hab mal alles ausgeschaltet und vom netzgenommen, usb abgeklemmt, anderen usb port genommen, wieder Spannung drauf, jetzt gehts, musste aber mit $X freischalten.

normal?

danke für deine hilfe!

**Comment by Schildkroet** [comment]
Ja, Homing ist standardmäßig ein.

**Comment by hitchhiker85** [comment]
ah super danke!

kurze frage!

was ist noch so alles geplant? backlash für A und B?

**Comment by Schildkroet** [comment]
Momentan sind keine großen Änderungen geplant. Backlash für A/B macht keinen Sinn, Wie soll eine lockere Achse bearbeitet werden??

**Comment by hitchhiker85** [comment]
Wenn man z.b. Umkehrspiel hat durch Schneckenwelle und Rad? weist was ich meine?

**Comment by hitchhiker85** [comment]
nabend!!!

sagmal gibts irgendwo eine einstellung um das $x nicht immer eingeben zu müssen?? danke

homing init disable oder?

**Comment by Schildkroet** [comment]
Ja, hab doch geschrieben das Homing aktiviert ist

**Comment by hitchhiker85** [comment]
ja aber kommentiere ich das ändert sich leider nichts daran. ich muss trotzdem immer freischalten. versteh ich nicht sorry

**Comment by Schildkroet** [comment]
Du musst die Settings im EEPROM auch aktualisieren
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands#rst-rst-and-rst--restore-grbl-settings-and-data-to-defaults

**Comment by hitchhiker85** [comment]
ja! hab ich!

könntest du mir bitte sagen welche werte in der config geändert werden müssen??

$22=0 hab ich auch!

danke

**Comment by Schildkroet** [comment]
Wenn $22=0 ist, dann kommt die Meldung nicht mehr. Gerade selbst am Board getestet

**Comment by hitchhiker85** [comment]
i h hab in der defaults.h 22=0

in der config.h //#homing_init_lock

was ist dann noch falsch?!

danke

**Comment by hitchhiker85** [comment]
hab das // entfernt nun gehts!

danke danke danke:) sry fürs nerven :)

**Comment by Schildkroet** [comment]
Was ist die Ausgabe bei `$$` ?

**Comment by hitchhiker85** [comment]
22=0

hab den eeprom gewiped per grbl plugin im cambam.

einzige sache die mich wundert ist:
in cambam zieht er sich die $$ nicht alleine.

jeder andere arduino mit grbl macht das.

weis ja nicvt ob du cambam mit dem plugin kennst.

welches cam programm nutzt du?

danke
