### ISSUE TITLE
port to STM32F411CEU6

### ISSUE THREAD

**Issue by creisey** [Schildkroet/GRBL-Advanced#33]
how hard is it to port your code to the black pill. its basicly the same core STM32F411....?

STM32F411CEU6

**Comment by Schildkroet** [comment]
Theoretically it should run out the box. But you might run out of pins if you use extended functionality.

**Comment by creisey** [comment]
when i flash the .bin file to it, it cant boot the code. only a factory reset will relieve it again.

**Comment by Schildkroet** [comment]
OK, might be because of the smaller size of the flash. Settings are stored in last sector of flash, which is missing here.
Try commenting out the Settings_Init-Function and try again.

**Comment by klembaris** [comment]
STM32F411CEU6 has 512 KB Flash and WeAct bootloader, but after .hex load there is no connection and com port.

**Comment by Schildkroet** [comment]
how do you flash the hex?

**Comment by klembaris** [comment]
With STM32 st-link
![st](https://user-images.githubusercontent.com/17252320/78295232-7af75480-7534-11ea-96db-312b6ea7f86e.png)

**Comment by Schildkroet** [comment]
It seems this board uses a 25MHz external crystal.

Go to HAL/STM32/stm32f4xx.h and change all HSE_VALUE from 8 to 25MHz and recompile

**Comment by klembaris** [comment]
Its same, not working.

**Comment by Schildkroet** [comment]
Are you sure you use UART2 on PA2/3?

**Comment by klembaris** [comment]
Now yes:), Usb to TTL dongle to ports A2 and A3. But still no response from controller.

**Comment by Schildkroet** [comment]
Connect st-link, Select Debug Target in Embitz and start a debug session to see if it runs

**Comment by klembaris** [comment]
Debugger-target tab: empty no logs
Debugger tab:

Building to ensure sources are up-to-date
Build succeeded
Selecting target: 
Debug
Adding file: bin\Debug\GRBL_Advanced.elf
Adding source dir: C:\Users\John\Desktop\GRBL-Advanced-software\
Adding source dir: C:\Users\John\Desktop\GRBL-Advanced-software\
Starting debugger: 
done
Setting breakpoints
EmBitz embedded firmware debugger for arm-none-eabi (Sep 30 2016/14:16:49).
Based on (GDB)  7.8.2 - License GPLv3+ by Gerard Zagema.
This program comes with ABSOLUTELY NO WARRANTY; for details type "show war".
This is free software, and you are welcome to redistribute it
under certain conditions; type "show cop" for details.

Reading symbols from bin/Debug/GRBL_Advanced.elf...
done.
Source directories searched: C:/Users/John/Desktop/GRBL-Advanced-software;$cdir;$cwd
Remote debugging using localhost:4242
0x000000000x00000000 in ?? ()
Connected
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...

**Comment by Schildkroet** [comment]
Can you debug this programm?
[TestF411CE.zip](https://github.com/Schildkroet/GRBL-Advanced/files/4425490/TestF411CE.zip)

**Comment by klembaris** [comment]
Sure, now looks like this:
![1](https://user-images.githubusercontent.com/17252320/78337125-305bf380-7599-11ea-82b0-3840948d6850.png)

**Comment by Schildkroet** [comment]
OK, another try with grbl-advanced:
Make sure HSE_VALUE is set to 25000000 in HAL/STM32/stm32f4xx.h

In HAL/STM32/system_stm32f4xx.c set PLL Parameters:

`/************************* PLL Parameters *************************************/
/* PLL_VCO = (HSE_VALUE or HSI_VALUE / PLL_M) * PLL_N */
#define PLL_M      25
#define PLL_N      168

/* SYSCLK = PLL_VCO / PLL_P */
#define PLL_P      2

/* USB OTG FS, SDIO and RNG Clock =  PLL_VCO / PLLQ */
#define PLL_Q      8`

Debug again.

**Comment by klembaris** [comment]
Everything works now. Thanks.

![1](https://user-images.githubusercontent.com/17252320/78342815-8bdeaf00-75a2-11ea-9513-85021e020d15.png)

**Comment by creisey** [comment]
sorry for my late reply. had to finalize the exposé for my master... i could also flash the firmware according your explanation. is the grbl only working through ttl dongle? or is there also a virtual com port solution? like on the bluepill?

**Comment by Schildkroet** [comment]
Only USART. No VCP.

**Comment by duembeg** [comment]
Hi, 
Just wanted to ask since the device (blackpill) is advertised as 100Mhz;
wondering if PLL_N should be 192 and SystemCoreClock = 100000000?

**Comment by hunabapr** [comment]
I get the same issue, ie "STM32F411CEU6 has 512 KB Flash and WeAct bootloader, but after .hex load there is no connection and com port"

I've followed this up to 3 Apr 2020 and was getting the same results including the connect to the test prog.
But when I make the changes re:HAL/STM32/stm32f4xx.h plus...   I still can't get this to work

Any ideas please?

Taken from ST-Link utility
14:31:15 : Device flash Size : 512KBytes
14:31:15 : Device family :STM32F411xC/E

The best   Paul

**Comment by hitchhiker85** [comment]
> Everything works now. Thanks.
> 
> ![1](https://user-images.githubusercontent.com/17252320/78342815-8bdeaf00-75a2-11ea-9513-85021e020d15.png)

hi you use the blackpill with stm32f411ce right?

possible to share your file???? thanks

**Comment by hitchhiker85** [comment]
> Only USART. No VCP.

is it realy not possible to use vcp?


i convert all to stm32f411ceu6.
gpios... hse.  it works fine with uart pa2 pa3.
but with the usb plug it would be perfect
