### ISSUE TITLE
list board

### ISSUE THREAD

**Issue by qiwalker** [Schildkroet/GRBL-Advanced#36]
hi... can i use others STM32 board such as
STM32F103 [ARM Cortex M3] or The STM32F407 [ARM Cortex M4] ?

thanks ^^

**Comment by qiwalker** [comment]
hi...one more question, where i can find pin limit for A and B axis ?

**Comment by Schildkroet** [comment]
Yes, it is possible, but you have to port some code.
https://github.com/Schildkroet/GRBL-Advanced/issues/33
https://github.com/Schildkroet/GRBL-Advanced/issues/12
https://github.com/Schildkroet/GRBL-Advanced/issues/8

Currently there are no limit pins for A&B. But they can be easily added.

**Comment by qiwalker** [comment]
thanks for your explanation,

any tutorial to add limit pin for A & B ?

**Comment by Schildkroet** [comment]
No, but should be enough to initialize pins in HAL/GPIO and add handling in grbl/Limits

**Comment by qiwalker** [comment]
ok i will try add code in those file, thank you very much...

**Comment by qiwalker** [comment]
hi again

at limit.c i add
	limit_state = (GPIO_ReadInputDataBit(GPIO_LIM_X_PORT, GPIO_LIM_X_PIN)<<X_LIMIT_BIT);
	limit_state |= (GPIO_ReadInputDataBit(GPIO_LIM_Y_PORT, GPIO_LIM_Y_PIN)<<Y_LIMIT_BIT);
	limit_state |= (GPIO_ReadInputDataBit(GPIO_LIM_Z_PORT, GPIO_LIM_Z_PIN)<<Z_LIMIT_BIT);
	limit_state |= (GPIO_ReadInputDataBit(GPIO_LIM_Z_PORT, GPIO_LIM_Z_PIN)<<A_LIMIT_BIT);
	limit_state |= (GPIO_ReadInputDataBit(GPIO_LIM_Z_PORT, GPIO_LIM_Z_PIN)<<B_LIMIT_BIT);

and at GPIO i add

#define GPIO_LIM_A_PORT			GPIOA
#define GPIO_LIM_B_PORT			GPIOA
#define GPIO_LIM_A_PIN			GPIO_Pin_0
#define GPIO_LIM_B_PIN			GPIO_Pin_1

is it correct ?

**Comment by Schildkroet** [comment]
limit_state |= (GPIO_ReadInputDataBit(**GPIO_LIM_Z_PORT**, **GPIO_LIM_Z_PIN**)<<A_LIMIT_BIT);
limit_state |= (GPIO_ReadInputDataBit(**GPIO_LIM_Z_PORT**, **GPIO_LIM_Z_PIN**)<<B_LIMIT_BIT);

Only if you set the correct defines

**Comment by qiwalker** [comment]
Correction
sorry, my mistake

	limit_state |= (GPIO_ReadInputDataBit(GPIO_LIM_Z_PORT, GPIO_LIM_A_PIN)<<A_LIMIT_BIT);
	limit_state |= (GPIO_ReadInputDataBit(GPIO_LIM_Z_PORT, GPIO_LIM_B_PIN)<<B_LIMIT_BIT);

is there any file need to edit sir ?

**Comment by qiwalker** [comment]
Correction
Sorry, my mistake

	limit_state |= (GPIO_ReadInputDataBit(GPIO_LIM_A_PORT, GPIO_LIM_A_PIN)<<A_LIMIT_BIT);
	limit_state |= (GPIO_ReadInputDataBit(GPIO_LIM_B_PORT, GPIO_LIM_B_PIN)<<B_LIMIT_BIT);

and i also add this line at config.h

#define HOMING_CYCLE_0 		    (1<<B_AXIS)
#define HOMING_CYCLE_1 		    (1<<A_AXIS)
#define HOMING_CYCLE_2 		    (1<<Z_AXIS)
#define HOMING_CYCLE_3 		    ((1<<X_AXIS)|(1<<Y_AXIS))

is there any file need to update sir ?

**Comment by Schildkroet** [comment]
> No, but should be enough to initialize pins in **HAL/GPIO** and add handling in **grbl/Limits**

And PA-0 and 1 are already occupied

**Comment by qiwalker** [comment]
Done Sir i change to PA-11 and 12

**Comment by datdadev** [comment]
Can you share the ported version of STM32F407VET6 chip?
