### ISSUE TITLE
backlash settings partly ignored when DEFAULT_HOMING_DIR_MASK not 0

### ISSUE THREAD

**Issue by c031917** [Schildkroet/GRBL-Advanced#37]
Hi,
thanks for your work - it could give me finally the backlash compensation I really need. I even switched to from Arduino2560 to STM32 for this..

I came across an effect that my backlash setting for X was set, but not for Y.
With the debugger I found out that this is caused in MC_Init in MotionControl.c 

void MC_Init(void)
{
    for(uint8_t i = 0; i < N_AXIS; i++)
    {
        dir_negative[i] = DIR_NEGATIV ^ (settings.homing_dir_mask & (1<<i));
    }  

When settings.homing_dir_mask is not zero, which is the case for my mill ("3" for X and Y inverted, not Z), dir_negative[] is {0;3;1;1;1} after init is done. But it should be {1;1;0;0;0}
This leads to always skipping Y backlash calculation further down, as this expression never becomes true when comparing to 3:

if(dir_negative[i] == DIR_NEGATIV)
 
I replaced the line in MC_Init with

dir_negative[i] =  1 & (settings.home_dir_mask >> i);

and now I get {1;1;0;0;0} in dir_negative[] and thus backlash compensation also on Y!

The line is not yet complete, as I dropped the "DIR_NEGATIV ^" part

Best Regards

Peter

**Comment by Schildkroet** [comment]
Thanks, i will look at it later.
