### ISSUE TITLE
Baud rate

### ISSUE THREAD

**Issue by steph79260** [Schildkroet/GRBL-Advanced#38]
Hello,

I don't understand why, but the baud rate must be set to 57600 for this to work. 
Yet we have 115200 in the config.h ...

Do you have any idea where this can come from?

Thank you and have a nice day, Stéphan

     -  My card : "NUCLEO F-411RE"
     -  Compiled with : "EMBITZ 1.11"
     -  Load with : "STM32 ST-LINK Utility"

**Comment by Schildkroet** [comment]
Your board runs only with half speed. Did you modify the clock source?

**Comment by steph79260** [comment]
No I didn't touch anything at the file source.
Maybe a jumper on the board ? But i've modifie nothing...

**Comment by Schildkroet** [comment]
I meant the board itself

**Comment by steph79260** [comment]
No

**Comment by Schildkroet** [comment]
Do you know how to debug?

**Comment by steph79260** [comment]
I can try...

**Comment by Schildkroet** [comment]
Set a breakpoint in HAL/STM32/system_stm32f4xx.c Line 398:
 (if (HSEStatus == (uint32_t)0x01))

Then single step to see if it continues in the following lines or if it jumps into else path in line 440

**Comment by steph79260** [comment]
Sorry, the breakpoint is well positioned but then I don't know where to go to debug this line ...

![image](https://user-images.githubusercontent.com/59112520/84594108-46ffb000-ae50-11ea-890f-12d9d34e4eff.png)

**Comment by Schildkroet** [comment]
Select "Debug"-Target at top, then press F8. Programm should stop at breakpoint. Press F10 for single step

**Comment by steph79260** [comment]
It's going to the line 401...

![image](https://user-images.githubusercontent.com/59112520/84594319-a611f480-ae51-11ea-8b24-3ffb2284f027.png)

**Comment by Schildkroet** [comment]
Ok, delete old breakpoint, set new breakpoint in SPL/src/stm32f4xx_rcc.c Line 1333. If programm stops in main, press F5, then it should stop at breakpoint. Hover mouse over HSE_VALUE. What value is displayed?

**Comment by steph79260** [comment]
When I do an F8 after putting a breakpoint line 1333 (stm32f4xx_rcc.c), it jumps directly to line 61 of the main.c ...

![image](https://user-images.githubusercontent.com/59112520/84594601-b3c87980-ae53-11ea-92c4-1fe0acc55c95.png)

**Comment by Schildkroet** [comment]
Thats why i said you should press F5

**Comment by steph79260** [comment]
![image](https://user-images.githubusercontent.com/59112520/84594757-b6779e80-ae54-11ea-8001-e69e2bc3b0eb.png)

**Comment by Schildkroet** [comment]
Go to HAL/STM32/stm32f4xx.h Line 148 and change 16 to 8

**Comment by steph79260** [comment]
![image](https://user-images.githubusercontent.com/59112520/84595135-bb3d5200-ae56-11ea-9891-2a66146a5d6c.png)


I change ((uint32_t)16000000) by ((uint32_t)8000000) ?

**Comment by Schildkroet** [comment]
yes

**Comment by steph79260** [comment]
Ok and after i compile and i load on the card ?

**Comment by Schildkroet** [comment]
yes

**Comment by steph79260** [comment]
Ok to 115200 !!
Thank you very much ;)
Steph
