### ISSUE TITLE
cambam grbl plugin

### ISSUE THREAD

**Issue by hitchhiker85** [Schildkroet/GRBL-Advanced#40]
Das grbl plugin in cambam erkennt nicht die grbl version bzw will sich nicht verbinden!
hast du eine lösung?

**Comment by Schildkroet** [comment]
Die Ausgabe ist identisch zu grbl. Andere GCode Sender wie UGS funktionieren bei mir auch problemlos. Daher muss es an irgendeiner speziellen Sache von diesem Plug-In liegen. Dementsprechend solltest du beim Ersteller dieses Plug-Ins nachfragen.  Ich kann dazu leider nichts sagen.

**Comment by hitchhiker85** [comment]
ich hab einfach  mal geguckt! sobald ich den reset knopf betätige am f411re funktioniert es!

gibt es eine zeile die ich ändern kann ohne den reset drücken zu müssen?
danke

**Comment by Schildkroet** [comment]
Nein, sobald das Board mit Spannung versorgt wird, startet es automatisch. Reset ist nur nach einem Flashvorgang nötig. Man könnte noch die Firmware vom Debugger updaten, da einige damit wohl Probleme hatten

**Comment by hitchhiker85** [comment]
weist du auf welche version?

ich muss definitiv jedesmal den reset drücken. auch im ugs. Danke

**Comment by Schildkroet** [comment]
Auf die neuste Version

**Comment by hitchhiker85** [comment]
hab ich gemacht, auch die letzte Version deiner hex Datei mit §rst=$.
es bleibt gleich.


noch eine Idee?
bekomme nun auch error 2.

danke

**Comment by Schildkroet** [comment]
Nein, nicht grbl. Du must die Firmware vom Debugger auf dem NucleoBoard updaten.

**Comment by hitchhiker85** [comment]
ich habe beides gemacht.

keine ahnung.
win updates sind deaktiviert.
was kann ich noch machen?
debugger ist grupdated und die neuste version grbl von dir.

ich hab nix verändert. mich wundert das. danke

**Comment by hitchhiker85** [comment]
ich hab jetzt mehrere programme ausprobiert.
ich muss tatsächlich immer reset drücken damit alles funktioniert.


hast du echt kein tipp?

**Comment by hitchhiker85** [comment]
oder weist du wie ich bei verbindung den reset automatisch hab?

irgend ein bit was gesetzt werden muss? nur im stcube find ich nichts.

**Comment by hitchhiker85** [comment]
problem gefunden!

es waren 2 0er Widerstände mit kalten lötstellen.
jetzt geht alles!
