### ISSUE TITLE
spindle control with Relay?

### ISSUE THREAD

**Issue by hitchhiker85** [Schildkroet/GRBL-Advanced#41]
hi! can you please say me what i must cange to control my spindle with relay?

i will only switch on and off.

thanks

**Comment by Schildkroet** [comment]
Update to newest version.
Use PB7/Spindle_Enable (See pinout_left) to control a relay.

**Comment by hitchhiker85** [comment]
i use pb7 but what must change in config?
thanks for your help!

**Comment by Schildkroet** [comment]
Nothing, except invert mask if neccessary

**Comment by hitchhiker85** [comment]
i dont need changes if i use relay on pb7?

and which values i must set i my cam tool?
m3 m5 nothing hapens.
with fresh hex file.

hope you can help me.

thanks



Von meinem Samsung Galaxy Smartphone gesendet.



-------- Ursprüngliche Nachricht --------
Von: Schildkroet <notifications@github.com>
Datum: 20.07.20 21:38 (GMT+01:00)
An: Schildkroet/GRBL-Advanced <GRBL-Advanced@noreply.github.com>
Cc: hitchhiker85 <herte@hotmail.de>, Author <author@noreply.github.com>
Betreff: Re: [Schildkroet/GRBL-Advanced] spindle control with Relay? (#41)


Nothing, except invert mask if neccessary

**Comment by Schildkroet** [comment]
No changes. M3 turns it on, M5 off. I tested this right now. Works perfectly

**Comment by hitchhiker85** [comment]
ok tomorrow i will erase the chip complete and try it again.

i use a cheap single relay shield.
i think i must change the high/low on/off option..

and spindle speed i dont change ? i mean $30?



thanks!



Von meinem Samsung Galaxy Smartphone gesendet.



-------- Ursprüngliche Nachricht --------
Von: Schildkroet <notifications@github.com>
Datum: 20.07.20 23:22 (GMT+01:00)
An: Schildkroet/GRBL-Advanced <GRBL-Advanced@noreply.github.com>
Cc: hitchhiker85 <herte@hotmail.de>, Author <author@noreply.github.com>
Betreff: Re: [Schildkroet/GRBL-Advanced] spindle control with Relay? (#41)


No changes. M3 turns it on, M5 off. I tested this right now. Works perfectly
