### ISSUE TITLE
grbl error 12 step rate greater than maximum supported.

### ISSUE THREAD

**Issue by doctorpartlow** [Schildkroet/GRBL-Advanced#43]
I'm sure I'm being dumb here, but I threw a new stepper driver on and set the microstepping to 4000, did some calibration and attempted to issue a $100=2554.206 and received the error in the screen shot.. 
![grbl error](https://user-images.githubusercontent.com/300006/89693237-ef277780-d8db-11ea-8539-bf25ca262f38.JPG)

I'm sure I could hunt it down in the code but is this meant to defaut at that low? or didn't I read something and there's a setting I have to change to remove the cap? 

what's the maximum resolution? I'll probably just lower the microstepping until I hear of a workaround

**Comment by Schildkroet** [comment]
The step rate is defined here:
https://github.com/Schildkroet/GRBL-Advanced/blob/b7a1d3010ee20b3cc830b7e003ae42d261910687/grbl/Config.h#L317
And also checked here:
https://github.com/Schildkroet/GRBL-Advanced/blob/b7a1d3010ee20b3cc830b7e003ae42d261910687/grbl/Stepper.c#L69-L73
It is currently 120 KHz, but higher frequencys should be no problem.
