### ISSUE TITLE
Question about hardware for stepper drivers

### ISSUE THREAD

**Issue by brunobasto** [Schildkroet/GRBL-Advanced#44]
This looks like an awesome project. It's fantastic that you've implemented backlash compensation. Such a needed feature for DIY / Hobby CNCs.

My question is: For standard Arduinos, there are several shields available that allow you to hook up stepper drivers to it. Like this one: 
![Screen Shot 2020-08-31 at 08 54 46](https://user-images.githubusercontent.com/156388/91717386-cd7e8080-eb67-11ea-9afd-b1c03b77cfc6.png)

What's your setup with STM32? What do you recommend? I see that you have a Hardware section in your README, but I couldn't understand from there how do you hook up your stepper drivers to the main board.

**Comment by Schildkroet** [comment]
The only real difference between Arduino and STM32 are the different voltage levels (5V <-> 3.3V). So if you use drivers, which can handle both voltages (e.g. TMC), there's no real difference.
Since i use external drivers and sensors with different voltage levels, i designed my own shield.
