### ISSUE TITLE
SPI driver

### ISSUE THREAD

**Issue by FELiXik** [Schildkroet/GRBL-Advanced#46]
Hello,
is there some simple way to use L6470 motor driver with GRBL advanced? I´m trying to investigate what place in code could be best for driving, but no any succes.

THX!

**Comment by Schildkroet** [comment]
Hello,
that depends on your usage and driver mode. GRBL is designed for a normal stepper interface, so you have to replace the stepper routines at least. For further information you should read the datasheet of the motor driver. I dont have experience with that kind of driver.

**Comment by J-Dunn** [comment]
FELiXik , are you still interested in using L6470?
