### ISSUE TITLE
DEFAULT_SYSTEM_INVERT_MASK and $0

### ISSUE THREAD

**Issue by PlanBV2** [Schildkroet/GRBL-Advanced#48]
Hello,

First, thanks again for all your work!

I don't want to bother you to mutch, but I recognized that when I set DEFAULT_SYSTEM_INVERT_MASK = 0 in default.h, $0 does not become 0. If I set $0 = 0 after compiling, it stays at zero. 
Also, I'm not completely sure what for the ENABLE_LIMITS and FORCE_HARD_LIMIT_CHECK flags are or what the difference to $21 (Hard limits) is.
Maybe you could put a small note in the readme about $0. Generally, I would support you with that, but since I don't understand $0 completely, I better don't write any documentation about it :D

Many thanks in advance!

**Comment by Schildkroet** [comment]
Hello,

yes, the behaviour is a bit unclear, but correct.
DEFAULT_SYSTEM_INVERT_MASK  is an EEPROM setting, so it doesn't change by setting it in source unless you reset the EEPROM. This applies to all $$ settings.

You can ignore the other flags. I used them for internal testing and they shouldn't be there :D
I will remove them probably
