### ISSUE TITLE
4 axis

### ISSUE THREAD

**Issue by enricoviale77** [Schildkroet/GRBL-Advanced#5]
is there a possibility to implement a 4 axis?

**Comment by Schildkroet** [comment]
Yes, that would be possible. But this project will only receive bugfixes since there is a better ARM version coming up.

**Comment by hdo** [comment]
Hey Schildkroet, where will the new ARM version be published? On GNEA?

**Comment by Schildkroet** [comment]
Yes, according to the description, it will be published at https://github.com/gnea/gnea
But i will fork it and add STM32 support

**Comment by hdo** [comment]
Ok great, thanks for feedback and Schöne Grüße ;-)

**Comment by enricoviale77** [comment]
very well! I can not wait! but does a forum exist? I have a lot of questions but I do not want to disturb here!

**Comment by Schildkroet** [comment]
Theres a discussion here: https://github.com/gnea/grbl/issues/67
Thats all i know
