### ISSUE TITLE
500 Khz

### ISSUE THREAD

**Issue by IhsanFuadi3** [Schildkroet/GRBL-Advanced#51]
Hi
in the nucleo f446 the speed of each axis can be up to 500 khz?
thanks before

**Comment by Schildkroet** [comment]
Hello,
i never tried, but i think it should be possible.
But you have to change max_step_rate https://github.com/Schildkroet/GRBL-Advanced/blob/software/grbl/Config.h#L313-L317

**Comment by IhsanFuadi3** [comment]
thank for you reply sir,
I change max_step_rate and F_CPU in util.h,and it's working

**Comment by Schildkroet** [comment]
You shouldn't change F_CPU unless you actually change the clock tree. Otherwise grbl won't calculate step rates etc correct

**Comment by IhsanFuadi3** [comment]
you mean possible miss step?

**Comment by Schildkroet** [comment]
No, wrong feedrate etc

**Comment by IhsanFuadi3** [comment]
oo i see,but if i just change max _step_rate,grbl only up to 250 khz,how i increase more than 250 khz?

**Comment by Schildkroet** [comment]
Double timer frequency here
https://github.com/Schildkroet/GRBL-Advanced/blob/software/HAL/TIM/TIM.c#L147-L155
https://github.com/Schildkroet/GRBL-Advanced/blob/software/grbl/util.h#L46

**Comment by IhsanFuadi3** [comment]
if may i know,how calculate timer frequancy,if I want 500 khz sir?

**Comment by Schildkroet** [comment]
what processor do you use?

**Comment by Schildkroet** [comment]
`TIM_TimeBaseStructure.TIM_Prescaler = 7-1;		// 24 MHz`

Change to :
`TIM_TimeBaseStructure.TIM_Prescaler = 3;		// 48 MHz`

`F_TIMER_STEPPER             48000000UL`

**Comment by IhsanFuadi3** [comment]
i use Nucleo F446 sir

**Comment by IhsanFuadi3** [comment]
is there any problem if i set max_step_rate to 500000 Khz sir?with your suggest frequency

**Comment by Schildkroet** [comment]
I didn't tried it yet. You have to find out yourself

**Comment by IhsanFuadi3** [comment]
Ok Sir,thanks for the reply
