### ISSUE TITLE
Does it support cutter radius compensation?

### ISSUE THREAD

**Issue by karoria** [Schildkroet/GRBL-Advanced#52]
I have seen in readme that this firmware supports G40 radius compensation. I know that the standard grbl doesn't support it. To make double sure, I am asking this question because I am badly in need of this feature.
Thanks in advance.

**Comment by Schildkroet** [comment]
Unfortunately no, this is copied from the original grbl. It seems it is listed as supported, because the parser reads the command and doesn't throw an error, but nothing is done.

**Comment by karoria** [comment]
Ok. Thanks for reply.
