### ISSUE TITLE
Step pulse invert

### ISSUE THREAD

**Issue by zab-ig** [Schildkroet/GRBL-Advanced#54]
Hello. Found the following problem.
I have inverted the control pulses, $ = 7. those. the stepping pulse switches from normal high to low for the pulse period and then returns back to high. Everything works well, but there is one problem:
If you press any button on the JOG panel (x + for example) and press the Stop button while moving the x axis, the step pulse does not return back to the high state after the motor stops. It becomes low on all axes, even if only one axis was moving when the stop button was pressed. If you press any button on the JOG panel again, and let the machine complete the movement and stop on its own, then the step impulse on all axes is set high as it should be.
If you do not press the stop button on the JOG panel, then everything works as expected. If you press the stop button, the inversion of control impulses does not work until the next start of movement. 

p.s. STM32F411

**Comment by Schildkroet** [comment]
Hello,
will be fixed with next version.
Thx
