### ISSUE TITLE
BUG -Unable to change $0

### ISSUE THREAD

**Issue by Zorki4** [Schildkroet/GRBL-Advanced#59]
https://github.com/Schildkroet/GRBL-Advanced/blob/c64d012f96bce1a5c4ecedae686ebfc3da7e61d8/grbl/Settings.c#L400

Hi,
It is unable to change $0 by the command line, because function is commented out. There shouldnt be // marks.

`//settings.system_flags = int_value;`

**Comment by Schildkroet** [comment]
This is intended since the pulse time (original $0) is fixed.
But i did some tests with internal flags, so i set them to $0, but thats not for normal users

**Comment by Zorki4** [comment]
YES. I know that it is used fos inverting control pins (hold, start etc.) and I've tried to change it :) Befere I found that it is commented out I had to modify deafults.h, recompile and reprogram Nucleo board.
