### ISSUE TITLE
invert coolant flood and spindle enable pin

### ISSUE THREAD

**Issue by alk1913** [Schildkroet/GRBL-Advanced#6]
hello,thanks for your great work,i begin to upgrade my cnc form arduino uno to stm32f411re,using your project.but i can't get work the invert coolant flood,i uncomment the define in config.h but not work.
and the spindle enable pin on D14 always remain in 0v.
thanks for your help!!

**Comment by Schildkroet** [comment]
It seems i forgot to add the config header. I added them now but hadn't time to test. See if it works now

**Comment by alk1913** [comment]
hello ,thanks for your work,i tested ,the invert coolant flood pin work fine,but the invert spindle enable pin doesn't work,the spindle enable pin D14 show always 0v.may be i doing something wrong?.
thanks for your help.

**Comment by Schildkroet** [comment]
Update to latest commit and enable **#define SPINDLE_ENABLE_OFF_WITH_ZERO_SPEED** in **Config.h**.

mfg
