### ISSUE TITLE
Makefile does not check .h files

### ISSUE THREAD

**Issue by J-Dunn** [Schildkroet/GRBL-Advanced#64]
The Makefile does not account for changes in any .h files 
```

touch grbl/System.h

bash-5.1$ make
make[1]: '/~/GRBL-Advanced/GRBL_Advanced.elf' is up to date.
make[1]: '/~/GRBL-Advanced/GRBL_Advanced.bin' is up to date.
make[1]: '/~/GRBL-Advanced/GRBL_Advanced.hex' is up to date.
make[1]: '/~/GRBL-Advanced/GRBL_Advanced.lst' is up to date.
   text    data     bss     dec     hex filename
  66868     492   12164   79524   136a4 /~/GRBL-Advanced/GRBL_Advanced.elf

```
```

#---------------------------------------------------------------------------------
# This rule links in binary data with the .c extension
#---------------------------------------------------------------------------------
%.c.o : %.c
#---------------------------------------------------------------------------------
  @echo $(notdir $<)
  @$(CC) $(FLAGS) $(CFLAGS) $(DEFINES) -c $^ -o $@


```
```

# Clear the implicit built in rules
#---------------------------------------------------------------------------------
.SUFFIXES:

```

Having cleared implicit rules it looks like it needs an explicit dependency rule for %.c.o (huh?) to %.h  and maybe at dep of everything on Config.h    

Is this your Makefile or a boilplate you dropped in from somewhere else. There seems to be some unused stuff for cpp and .S files.

**Comment by J-Dunn** [comment]
I've been digging into how to do this and it is incredibly arcane and esoteric to achieve such a simple and bleedingly obvious requirement. 

In fact it seems that this boiler plate was intended to produce dependency files and include them but the dependency rule for .d files is missing. 

```
DEPENDS     :=  $(OFILES:.o=.d)
......
-include $(DEPENDS)

```
The relevant incantation and  hieroglyphics are provided here:

http://www.gnu.org/software/make/manual/make.html#Automatic-Prerequisites

**Comment by Schildkroet** [comment]
I know this problem exists, but i'm far from an expert in makefiles. And it only takes 2-3s for a complete rebuild, so it is not a real problem for me.
If you have a feasable solution, you can ofc tell me
