### ISSUE TITLE
I2C - EEPROM

### ISSUE THREAD

**Issue by ClockedLogic** [Schildkroet/GRBL-Advanced#71]
A little background first.  I have designed a PCB with an STM32F405RG6 , a couple of stepper drivers and an I2C EEPROM  connected to IC21 I'm wondering if  the EEPROM code for writing config to external memory has been tested.  ?

**Comment by Schildkroet** [comment]
Hello,
yes, i'm using external eeprom since it was added. For me it is working without problem.

**Comment by ClockedLogic** [comment]
OK Thanks. I need to check the F405 core that I generated. I suspect I2C isn't configured correctly.  I have I2C on PB6 and PB7.

**Comment by Schildkroet** [comment]
Please make sure to use an compatible eeprom e.g. https://www.st.com/en/memories/m24c08-w.html
