### ISSUE TITLE
GCode Senders - What are you using?

### ISSUE THREAD

**Issue by ClockedLogic** [Schildkroet/GRBL-Advanced#72]
I have a version of UGS (Universal GCode Sender) that I modified to use the extra two axis (A and B)  for another project. Is anyone interested or are you happy with what you are using. 

I find UGS to be quite a good tool and recommend it . It needs Java 8 JRE or later and runs on most platforms, possibly even RPI but haven't tested it.

**Comment by Schildkroet** [comment]
For full feature support, you should use Candle 2 https://github.com/Schildkroet/Candle2
