### ISSUE TITLE
Targeting other STM32F4XX MCUs is there a how to?

### ISSUE THREAD

**Issue by ClockedLogic** [Schildkroet/GRBL-Advanced#73]
I cloned the main soruce for GRBL Advanced and created my own core for STMF405 as I couldn't see how to add support for it under the main project source tree . This is due to my lack of understanding of EmBitz and how to configure it.  How are other MCUs supported through the main source tree?

**Comment by Schildkroet** [comment]
This question was already asked several times e.g.
https://github.com/Schildkroet/GRBL-Advanced/issues/19
https://github.com/Schildkroet/GRBL-Advanced/issues/33

Basically you have to edit defines in project settings and modify clock tree if it doesnt match your mcu
