### ISSUE TITLE
Stepper Timing

### ISSUE THREAD

**Issue by ClockedLogic** [Schildkroet/GRBL-Advanced#74]
Hi SchildKroet,
Can you tell me what the valid values are for  F_TIMING_STEPPER in  https://github.com/Schildkroet/GRBL-Advanced/blob/software/grbl/util.h please.  I'm not certain what this should contain It seems to be 1/4 of the CPU clock where the existing value is 24000000 and the F_CPU is 96000000. 

CPU frequency on my board is 168MHz
does this mean I should set  F_CPU = 168000000 and F_TIMING_STEPPER = 42000000 ??

**Comment by Schildkroet** [comment]
This is the frequency of the stepper interrupt timer
https://github.com/Schildkroet/GRBL-Advanced/blob/software/HAL/TIM/TIM.c#L192
