### ISSUE TITLE
Core XY not supporting

### ISSUE THREAD

**Issue by trkadam58** [Schildkroet/GRBL-Advanced#78]
Hi,. If change to CoreXY , and compile it's showing error #

**Comment by Schildkroet** [comment]
Please try the latest commit

**Comment by trkadam58** [comment]
Sir,

There is still problem in CORE XY , after changes to CORE XY firmware not supporting, there is not having movement in motor,
for corexy changes some line un comment as below.


![1](https://user-images.githubusercontent.com/96012164/146634137-c00a7b06-99d4-423a-9933-a8e5e1a856c2.jpg)
![2 - ](https://user-images.githubusercontent.com/96012164/146634138-2713bdea-d847-4046-8375-b44a15f27cda.jpg)
