### ISSUE TITLE
CoreXY mode Not working

### ISSUE THREAD

**Issue by trkadam58** [Schildkroet/GRBL-Advanced#80]
When I have changed to CoreXY in  config.c file to #define COREXY. Firmware not working with software.

**Comment by Schildkroet** [comment]
Can you please explain more in detail what is not working?

**Comment by trkadam58** [comment]
- Please check below attached images,  i have changed  some line for COREXY and compiled, while compiling there is not have any error but Grbl advance not supporting with STM32F466RE. 


![2 - ](https://user-images.githubusercontent.com/96012164/146760950-b90daefa-352d-4683-8177-834c11eb732a.jpg)
![1](https://user-images.githubusercontent.com/96012164/146760953-0302d88a-4dc4-47c4-837e-d9a854291ae7.jpg)

**Comment by Schildkroet** [comment]
Please try the current commit

**Comment by trkadam58** [comment]
I have taken trial with new code it is working fine,
Thanks

**Comment by trkadam58** [comment]
Today I have taken trial with laser cutting software
 LIGHT BURN software, it is working perfectly,

**Comment by trkadam58** [comment]
Good morning, 
 I am very happy with your coding, so i want to make some small donation, but i not find the any link, please share payment link to trkadam58@gmail.com.

Thanking you,
Tukaram
