### ISSUE TITLE
What is the point of external EEPROM?

### ISSUE THREAD

**Issue by MarkHerhold** [Schildkroet/GRBL-Advanced#82]
Hi there, 

Just found this project. Great code quality. I purchased a STM32F411 and was able to compile and load the software on my Mac and it works!

I noticed that there's support for an external EEPROM module but I don't know why we would need an external one. Maybe to prevent overwrites between flashes?

**Comment by Schildkroet** [comment]
Hello,
Flash can only be written in entire pages, so it is very slow and you are wasting memory. And it is possible to lose your previous settings while flashing new firmware.
Otherwise it doesnt matter.
